import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { useSession, getSession, signOut } from 'next-auth/react'
import { FaChevronLeft } from "react-icons/fa"

export default function Account() {
  const { data: session } = useSession()

  return (
    <>
      <Head>
        <title>Account | Next Auth</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <>
        {session ? (
          <>
            <h1 className="text-3xl text-red-500 font-bold mb-3">
              Welcome {session.user.name}!
            </h1>
            <h3 className='text-xl font-semibold text-red-700 mb-3'>
              ** This is a protected page. You can only see this page if you are signed in. **
            </h3>
            <Image
              src={session.user.image}
              alt={session.user.name}
              width={50}
              height={50}
              className="rounded-full mb-3"
            />
            <p className='text-xl text-gray-900 font-light mb-6'>
              Signed In as {' '}
              <span className='font-semibold'>
                {session.user.email}
              </span>
            </p>
            <button
              className='bg-slate-300 rounded-md py-2 px-4'
              onClick={() => signOut()}
            >
              <span className='text-black text-base'>
                Sign Out
              </span>
            </button>
            <Link href='/'>
              <p className='text-blue-700 font-normal flex items-center gap-1 mt-6'>
                <FaChevronLeft className='text-[14px]' />
                <span className='text-base'>
                  Home
                </span>
              </p>
            </Link>
          </>
        ) : (
          <p className='text-xl text-center font-medium'>
            You are not signed in.
          </p>
        )}
      </>
    </>
  )
}

export async function getServerSideProps(context) {
  const session = await getSession(context)

  if (!session) {
    return {
      redirect: {
        destination: '/',
        permanent: false
      },
    }
  }

  return {
    props: {
      session
    },
  }
}
