import Head from 'next/head'
import Link from 'next/link'
import {
  useSession,
  getProviders,
  signIn,
  signOut
} from "next-auth/react"
import {
  FaGithub,
  FaGoogle,
  FaChevronRight
} from "react-icons/fa"

export default function Home({ providers }) {
  const { data: session } = useSession()
  console.log('session:', session)

  console.log('providers:', providers)

  return (
    <>
      <Head>
        <title>Home | Next Auth</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <>
        {session && (
          <>
            <h1 className="text-3xl text-red-500 font-bold mb-3">
              Hello {session.user.name}!
            </h1>
            <Link href='/account'>
              <p className='text-blue-700 font-normal flex items-center gap-1 mb-6'>
                <span className='text-base'>
                  Account
                </span>
                <FaChevronRight className='text-[14px]' />
              </p>
            </Link>
            <button
              className='bg-slate-300 rounded-md py-2 px-4'
              onClick={() => signOut()}
            >
              <span className='text-black text-base'>
                Sign Out
              </span>
            </button>
          </>
        )}
        {!session && (
          <>
            <h1 className="text-3xl text-red-500 font-bold mb-3">
              Hello World!
            </h1>
            <div className='flex flex-wrap items-center gap-4'>
              <button
                className='bg-slate-300 rounded-md py-2 px-4 flex items-center gap-2'
                onClick={() => signIn('github')}
              >
                <span className='text-black text-base'>
                  Sign In with GitHub
                </span>
                <FaGithub />
              </button>
              <button
                className='bg-slate-300 rounded-md py-2 px-4 flex items-center gap-2'
                onClick={() => signIn('google')}
              >
                <span className='text-black text-base'>
                  Sign In with Google
                </span>
                <FaGoogle />
              </button>
            </div>
          </>
        )}
      </>
    </>
  )
}

export async function getServerSideProps() {
  const providers = await getProviders()

  return {
    props: {
      providers
    }
  }
}
